title: Biopragmatics
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  Unraveling complex biology with biological knowledge graphs

twitter_username: cthoyt
github_username:  cthoyt
linkedin_username: cthoyt

url: "https://cthoyt.com"

google_analytics: UA-166029785-1

paginate: 5
paginate_path: "/blog/page:num/"
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
